---
title: "CD69 Dose Response"
author: "Matthew Wither"
date: "1/1/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library loads
```{r}
library(DescTools)
library(ggplot2)
library(ggridges)
library(dplyr)
library(ggpubr)
library(RColorBrewer)
library(gplots)
library(cluster)
library(zoo)
library(dendextend)
library(drc)

theme_set(theme_bw())


```

Jurkat data
```{r}
dir <- "/Users/matthewjwither/Desktop/R/CD69"
setwd(dir)

cd69 <- read.csv("CD69_AllReplicates.csv", header = TRUE)
cd69$Affinity <- as.factor(cd69$Affinity)
cd69 <- subset(cd69, Dose != 0)

#Convert dose to pmol
cd69$Dose <- cd69$Dose*2

col.affinities <- c("darkorchid3", "#E38E14")

#Curve fitting with 'drc' package
affinities <- c(2.3, 19)
ECs <- vector()
MFI_EC50 <- vector()
for (i in 1:length(affinities)) {
  fit <- drm(MFI ~ Dose, data = subset(cd69, Affinity == affinities[i]), fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
  EC50 <- ED(fit, 50, interval = "delta")[1,1]
  ECs[i] <- EC50
  
  #Get predicted MFI for the EC50s
  pred_MFI <- cd69[1,c(1,3)]
  pred_MFI$MFI <- NA
  pred_MFI$Dose <- EC50
  MFI_EC50[i] <- predict(fit, newdata = pred_MFI, se = F)
}

#Normalize each curve to the EC50
cd69$MFI_norm <- NA
affinity_split <- split(cd69, cd69$Affinity)
for (i in 1:length(affinity_split)) {
  temp <- affinity_split[[i]]
  temp$MFI_norm <- temp$MFI/MFI_EC50[i]
  affinity_split[[i]] <- temp
}
cd69_norm <- bind_rows(affinity_split)

#Convert dose to pmol
cd69_norm$Dose <- cd69_norm$Dose*2

ggplot(data = cd69, aes(x = Dose, y = MFI, color = Affinity)) +
  geom_point(size = 1)+
  coord_trans(x="log10") +
  #geom_text(aes(label=Dose)) +
  geom_vline(aes(xintercept = ECs[1]), color = col.affinities[1], linetype = "dashed") +
  geom_vline(aes(xintercept = ECs[2]), color = col.affinities[2], linetype = "dashed") +
  #scale_x_continuous(breaks=c(round(ECs[1], 2), round(ECs[2], 2), .01, 10, 50)) +
  scale_x_continuous(breaks=c(.02, 0.2, 2, 20, 80)) +
  stat_smooth(method = "drm", method.args = list(fct = LL.4()), se = FALSE) +
  scale_color_manual(name = "Antigen Affinity",
                     labels = c("Agonist (Kd ~ 2.3 uM)",
                                "Partial Agonist (Kd ~ 19 uM)"),
                     values = col.affinities) +
  labs(x = "Dose (pmol)", y = "CD69 MFI") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(),axis.title = element_text(size = 14, face = "bold"),
        panel.grid.minor = element_blank(), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))

ggplot(data = cd69_norm, aes(x = Dose, y = MFI_norm, color = Affinity)) +
  geom_point(size = 1, show.legend = F)+
  coord_trans(x="log10") +
  #geom_text(aes(label=Dose)) +
  geom_hline(aes(yintercept = 1), linetype = "dashed") +
  
  geom_vline(aes(xintercept = 0.2), alpha = 0.5) +
  geom_vline(aes(xintercept = 2), alpha = 0.5) +
  geom_vline(aes(xintercept = 20), alpha = 0.5) +
  geom_vline(aes(xintercept = 80), alpha = 0.5) +
  
  
  scale_x_continuous(breaks=c(.02, 0.2, 2, 20, 80)) +
  stat_smooth(method = "drm", method.args = list(fct = LL.4()), se = FALSE, show.legend = F) +
  scale_color_manual(name = "Antigen Affinity",
                     labels = c("Agonist (Kd ~ 2.3 uM)",
                                "Partial Agonist (Kd ~ 19 uM)"),
                     values = col.affinities) +
  labs(x = "pmol", y = "CD69 MFI (norm)") +
  facet_wrap(~Affinity) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(),axis.title = element_text(size = 14, face = "bold"),
        panel.grid.minor = element_blank(), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))


  
  

```

Primary Cells
```{r}

dir <- "/Users/matthewjwither/Desktop/R/CD69"
setwd(dir)

cd69 <- read.csv("CD69_Primary.csv", header = TRUE)
cd69$Affinity <- as.factor(cd69$Affinity)
cd69 <- subset(cd69, Dose != 0)

#Convert dose to pmol
cd69$Dose <- cd69$Dose*2

col.affinities <- c("darkorchid3", "#E38E14")

#Curve fitting with 'drc' package
naive <- subset(cd69, Subset == "Naive")
mem <- subset(cd69, Subset == "Memory")

affinities <- c(2.3, 19)

ECs_naive <- vector()
for (i in 1:length(affinities)) {
  fit <- drm(MFI ~ Dose, data = subset(naive, Affinity == affinities[i]), fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
  EC50 <- ED(fit, 50, interval = "delta")[1,1]
  ECs_naive[i] <- EC50
}

ECs_mem <- vector()
for (i in 1:length(affinities)) {
  fit <- drm(MFI ~ Dose, data = subset(mem, Affinity == affinities[i]), fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
  EC50 <- ED(fit, 50, interval = "delta")[1,1]
  ECs_mem[i] <- EC50
}

cd69 <- bind_rows(naive,mem)


ggplot(data = cd69, aes(x = Dose, y = MFI, color = Affinity, linetype = Subset)) +
  geom_point(size = 1)+
  coord_trans(x="log10") +
  
  geom_vline(aes(xintercept = ECs_naive[1]), color = col.affinities[1], linetype = "dashed") +
  geom_vline(aes(xintercept = ECs_naive[2]), color = col.affinities[2], linetype = "dashed") +
  
  geom_vline(aes(xintercept = ECs_mem[1]), color = col.affinities[1], linetype = "solid") +
  geom_vline(aes(xintercept = ECs_mem[2]), color = col.affinities[2], linetype = "solid") +
  
  scale_x_continuous(breaks=c(.02, 0.2, 2, 20, 80)) +
  stat_smooth(method = "drm", method.args = list(fct = LL.4()), se = FALSE) +
  scale_color_manual(name = "Antigen Affinity",
                     labels = c("Agonist (Kd ~ 2.3 uM)",
                                "Partial Agonist (Kd ~ 19 uM)"),
                     values = col.affinities) +
  labs(x = "Dose (pmol)", y = "CD69 MFI") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(),axis.title = element_text(size = 14, face = "bold"),
        panel.grid.minor = element_blank(), axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))




```